### ISSUE TITLE
your indexed records for ABRS 2009. Australian Faunal Directory. Zygorhynchus robertsoni. Australian Biological Resources StudyNode, Canberra. Accessed at <http://biodiversity.org.au/afd/taxa/d3298ef3-ea31-4f05-9da1-3b1d77bb197d> on 16 Mar 2021.

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/said#1]
Hi!

Thanks for helping to make existing biotic interaction data easier to find and access!

I was just looking at your GloBI indexed record at https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fsiad&interactionType=ecologicallyRelatedTo and I was wondering about ... why the Australian Faunal Directory links no longer resolve.

E.g., http://biodiversity.org.au/afd/taxa/d3298ef3-ea31-4f05-9da1-3b1d77bb197d no longer used to resolve to an indexed taxon, but no longer does so today (see attached screenshot)

![Screenshot from 2021-03-17 12-31-18](https://user-images.githubusercontent.com/1084872/111527187-e2de8500-871c-11eb-81e5-eb75cdce3eee.png)

related issue https://github.com/AtlasOfLivingAustralia/bie-index/issues/187 .

@nickdos @charvolant am open to suggestions how to migrate defunct/deprecated AFD links like  http://biodiversity.org.au/afd/taxa/d3298ef3-ea31-4f05-9da1-3b1d77bb197d .

**Comment by nickdos** [comment]
The biodiversity.org.au domain was down but they fixed whatever was broken and those links are resolving again.

**Comment by jhpoelen** [comment]
@nickdos thanks for your response. 

It appears that their site is back up, but the taxon pages are not current resolving (see attached screenshot associated with http://biodiversity.org.au/afd/taxa/d3298ef3-ea31-4f05-9da1-3b1d77bb197d accessed at 2021-03-17). 

Please let me know if you have any suggestions on who to contact about these suspicious "taxon missing" pages. 

![Screenshot from 2021-03-17 15-37-59](https://user-images.githubusercontent.com/1084872/111547812-f5fe4e80-8736-11eb-8862-9712ba719ac1.png)

**Comment by nickdos** [comment]
@jhpoelen AFD are not very good at resolving old identifiers and they tend to mint new identifiers when ever that part of the tree changes in their backbone. 

Luckily the ALA does try and track identifier changes and we issue a permanent redirect when we know an identifier has changed in a one-to-one way. Our URL scheme is slightly different for AFD taxa:

http://biodiversity.org.au/afd/taxa/d3298ef3-ea31-4f05-9da1-3b1d77bb197d
to
https://bie-ws.ala.org.au/ws/species/urn:lsid:biodiversity.org.au:afd.taxon:d3298ef3-ea31-4f05-9da1-3b1d77bb197d 
which redirects (301) to:
https://bie-ws.ala.org.au/ws/species/urn:lsid:biodiversity.org.au:afd.taxon:05adfc56-89c4-4050-95de-6d5f7991ee9f

Note the UUID part of the URL is the same and you should be able to extract it with a simple `substr` or `regex`.

**Comment by jhpoelen** [comment]
Interesting! Great to see that ALA and AFD are connected this way.

Hmm. I'll have to figure out what to do here, especially because some of the AFD urls do re-direct/resolve (e.g.,https://biodiversity.org.au/afd/taxa/f9dc0658-c918-4352-8ea8-02a309e988f9 redirects to https://biodiversity.org.au/afd/taxa/0076b670-3575-4397-ad73-12be82e8561d )  and their page contain useful information (e.g., host taxa). 

Thanks again for providing the context and examples!

![Screenshot from 2021-03-17 16-04-39](https://user-images.githubusercontent.com/1084872/111550281-087a8700-873b-11eb-8c68-52eda1dceb9a.png)

**Comment by nickdos** [comment]
You should be able to use the ALA URL-redirect as fall-back and then grab the new UUID and it will resolve on the AFD site. 

E.g. https://bie-ws.ala.org.au/ws/species/urn:lsid:biodiversity.org.au:afd.taxon:05adfc56-89c4-4050-95de-6d5f7991ee9f to https://biodiversity.org.au/afd/taxa/05adfc56-89c4-4050-95de-6d5f7991ee9f

**Comment by jhpoelen** [comment]
Very cool! I'll try it out. 

I'll close this issue as I described the needed functionality at https://github.com/globalbioticinteractions/globalbioticinteractions/issues/618 . Am hoping to take this as an opportunity to handle other cases of no longer supported terms / urls / name etc in need of custom redirection.

Many thanks for discussion and sharing your insights.
